#开发环境
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://139.199.86.11:5432/cook?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: postgres
    password: admin
    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
security:
  oauth2:
    client:
      client-id: cook
      client-secret: cookSecret
  basic:
  #关闭security
    enabled: false

cook.security.token: true
cook.social: true
cook.social.filterProcessesUrl: /qqLogin
cook.social.qq: true
cook.social.weiXin: true

cook:
  social:
    qq:
      app-id: 100550231
      app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
      provider-id: callback.do
    weiXin:
      app-id: wxd99431bbff8305a0
      app-secret: 60f78681d063590a469f1b297feff3c4
      provider-id: weiXin