#开发环境
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://139.199.86.11:5432/cook?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: postgres
    password: admin
    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
security:
  oauth2:
    client:
      client-id: cook
      client-secret: cookSecret
  basic:
  #关闭默认安全
    enabled: false

cook.security.token: true

#开启第三方
cook.social: true
#qq
cook.social.qq: true
#微信
cook.social.weiXin: true
#微博
cook.social.weiBo: false
cook.social.filterProcessesUrl: /qqLogin

#允许域跨站请求
cook.Access-Control-Allow-Origin: '*'

cook:
  social:
    qq:
      app-id: 100550231
      app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
      provider-id: callback.do
    weiXin:
      app-id: wxd99431bbff8305a0
      app-secret: 60f78681d063590a469f1b297feff3c4
      provider-id: weiXin
    weiBo:
      app-id: 100550231
      app-secret: 60f78681d063590a469f1b297feff3c4
      provider-id: weiBo
  image:
    #服务器里图片所在路径
    upload-path: /home/www
    #需要验证图片验证码的请求路径
    authenticateUrl: /authentication/image
  sms:
    #需要验证短信验证码的请求路径
    authenticateUrl: /authentication/sms
